# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 吴灿的博客
subtitle:
description:
author: 吴灿
language: zh
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://wucan.cc
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/ landscape
theme: maupassant

# Maupassant Theme Config
## docs:https://www.haomwei.com/technology/maupassant-hexo.html
fancybox: true ## If you want to use fancybox please set the value to true
duoshuo: wucanblog
# disqus: ## Your disqus_shortname, e.g. username
google_search: true
baidu_search: true
# swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
# tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
google_analytics: UA-72891077-1
# baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-about
  - page: rss
    directory: atom.xml
    icon: icon-rss

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - recent_comments
  - links

links:
  - title: site-name1
    url: http://www.baidu.com/
  - title: site-name2
    url: http://www.so.com/
  - title: site-name3
    url: http://www.sogou.com/

# Static files
js: js
css: css

# Theme version
version: 0.0.0

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git
  repository: git@github.com:wucangeo/wucangeo.github.io.git
  branch: master
